=== galvezzzz/DAM/Lenguaje de marcas/xml/ExamenSchema/Examen.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:annotation>
    <xs:appinfo>Validador</xs:appinfo>
    <xs:documentation>Este schema permite validar el documento XML</xs:documentation>
</xs:annotation>

    <xs:element name="nodos">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="router"></xs:element>
                    <xs:element ref="impresora"></xs:element>
                    <xs:element ref="ordenador"></xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Elementos-->
    <xs:element name="router">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="precio" type="pre"></xs:element>
                <xs:element name="direccionip"></xs:element>
                <xs:element name="ancho_banda" type="ancho" minOccurs="0"></xs:element>
            </xs:sequence>
            <xs:attribute name="NS" type="numerosocial"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="impresora">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="precio" type="pre"></xs:element>
                <xs:element name="color" type="c"></xs:element>
            </xs:sequence>
            <xs:attribute name="modelo" type="model"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="ordenador">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="precio" type="pre"></xs:element>
                <xs:element name="sistemaoperativo" type="so"></xs:element>
                <xs:element name="procesador" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="memoria" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="discoduro" minOccurs="0" maxOccurs="1"></xs:element>
            </xs:sequence>
            <xs:attribute name="fechainstalacion" type="fecha"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Restricciones-->
    <xs:simpleType name="ancho">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:fractionDigits value="0"></xs:fractionDigits>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="pre">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"></xs:fractionDigits>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="numerosocial">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]{6}[0-9]{5}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="model">
        <xs:restriction base="xs:string">
            <xs:enumeration value="laser"></xs:enumeration>
            <xs:enumeration value="tinta"></xs:enumeration>
            <xs:enumeration value="termica"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="c">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="imp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Epson"></xs:enumeration>
            <xs:enumeration value="Kyocera"></xs:enumeration>
            <xs:enumeration value="HP"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="so">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Windows"></xs:enumeration>
            <xs:enumeration value="MacOS"></xs:enumeration>
            <xs:enumeration value="Linux"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fecha">
        <xs:restriction base="xs:date"/>
    </xs:simpleType>
</xs:schema>

=== galvezzzz/DAM/Lenguaje de marcas/xml/ExamenSchema/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>

<nodos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Examen.xsd">

    <router NS = "AbCdEf12345">
        <precio>210.15</precio>
        <direccionip>192.168.1.10</direccionip>
    </router>
    <impresora modelo="laser">Epson
        <precio>120.22</precio>
        <color>true</color>
    </impresora>
    <ordenador>
        <precio>650.50</precio>
        <sistemaoperativo fechainstalacion="2022-01-02">Windows</sistemaoperativo>
        <procesador fabricante="Intel">i5</procesador>
        <memoria unidad="GB">8</memoria>
        <discoduro>1024</discoduro>
    </ordenador>
</nodos>
