=== galvezzzz/DAM/Lenguaje de marcas/xml/ExamenDTD/Ejercicio1_Curso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listacursos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cursos" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumnos" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dni" type="xs:string" />
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="apellido" maxOccurs="unbounded"
                                            type="xs:string" />
                                        <xs:element name="asignaturas" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string" />
                                                    <xs:element name="horas" type="xs:string" />
                                                    <xs:element name="profesor">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nrp"
                                                                    type="xs:string" />
                                                                <xs:element name="nombre"
                                                                    type="xs:string" />
                                                                <xs:element name="apellido"
                                                                    maxOccurs="unbounded"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="codigo" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="curso" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== galvezzzz/DAM/Lenguaje de marcas/xml/ExamenDTD/Ejercicio1_Curso.xml
<?xml version="1.0" encoding="UTF-8"?>

<listacursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Ejercicio1_Curso.xsd">
    <cursos curso="2DAM">
        <alumnos>
            <dni>333333R</dni>
            <nombre>Juan</nombre>
            <apellido>Garcia</apellido>
            <apellido>Garcia</apellido>
            <asignaturas codigo="c1">
                <nombre>Programacion</nombre>
                <horas>6</horas>
                <profesor>
                    <nrp>33</nrp>
                    <nombre>David</nombre>
                    <apellido>Pimentel</apellido>
                </profesor>
            </asignaturas>
        </alumnos>
        <alumnos>
            <dni>333333E</dni>
            <nombre>Pepe</nombre>
            <apellido>Viyuela</apellido>
            <asignaturas codigo="c2">
                <nombre>Lenguaje de marcas</nombre>
                <horas>6</horas>
                <profesor>
                    <nrp>24</nrp>
                    <nombre>Leandro</nombre>
                    <apellido>Morales</apellido>
                    <apellido>Vilchez</apellido>
                </profesor>
            </asignaturas>
        </alumnos>
    </cursos>

        
    <cursos curso="1DAM">
        <alumnos>
            <dni>333333A</dni>
            <nombre>Ronaldo</nombre>
            <apellido>Nazario</apellido>
            
            <asignaturas codigo="c3">
                <nombre>Bases de datos</nombre>
                <horas>6</horas>
                <profesor>
                    <nrp>12</nrp>
                    <nombre>Alejandro</nombre>
                    <apellido>Romero</apellido>
                </profesor>
            </asignaturas>

            <asignaturas codigo="c4">
                <nombre>Entornos de desarrollo</nombre>
                <horas>6</horas>
                <profesor>
                    <nrp>12</nrp>
                    <nombre>Alejandro</nombre>
                    <apellido>Romero</apellido>
                </profesor>
            </asignaturas>
        </alumnos>
    </cursos>
</listacursos>
