=== galvezzzz/DAM/Lenguaje de marcas/xml/ExamenDTD/prueba.dtd
<!ELEMENT listado (futuro+, divisa+, bono+, letra+)>
 <!ATTLIST futuro precio CDATA #REQUIRED>
 <!ATTLIST divisa precio CDATA #REQUIRED>
 <!ATTLIST bono precio CDATA #REQUIRED>
 <!ATTLIST letra precio CDATA #REQUIRED>
 <!ELEMENT ciudad_procedencia (madrid|nyork|frankfurt|tokio)>
 <!ELEMENT madrid EMPTY>
 <!ELEMENT nyork EMPTY>
 <!ELEMENT frankfurt EMPTY>
 <!ELEMENT tokio EMPTY>
 <!ATTLIST divisa estable CDATA #IMPLIED>
 <!ATTLIST bono estable CDATA #IMPLIED>
 <!ELEMENT futuro (producto, mercado?, ciudad_procedencia)>
 <!ELEMENT producto (#PCDATA)>
 <!ELEMENT mercado (#PCDATA)>
 <!ELEMENT bono (pais_de_procedencia,valor_deseado,
 valor_minimo, valor_maximo, 
ciudad_procedencia)>
 <!ELEMENT valor_deseado (#PCDATA)>
 <!ELEMENT valor_minimo (#PCDATA)>
 <!ELEMENT valor_maximo (#PCDATA)>
 <!ELEMENT pais_de_procedencia (#PCDATA)>
 <!ELEMENT divisa (nombre_divisa,
 tipo_de_cambio+, ciudad_procedencia)>
 <!ELEMENT nombre_divisa (#PCDATA)>
 <!ELEMENT tipo_de_cambio (#PCDATA)>
 <!ELEMENT letra (tipo_de_interes, 
pais_emisor,ciudad_procedencia)>
 <!ELEMENT tipo_de_interes (#PCDATA)>
 <!ELEMENT pais_emisor (espania|eeuu|alemania|japon)>
 <!ELEMENT espania EMPTY>
 <!ELEMENT eeuu EMPTY>
 <!ELEMENT alemania EMPTY>
 <!ELEMENT japon EMPTY>

=== galvezzzz/DAM/Lenguaje de marcas/xml/ExamenDTD/Ejercicio3_bolsa.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE listado SYSTEM "./prueba.dtd">

<listado>
    <futuro precio="9">
        <producto>Balon</producto>   
        <ciudad_procedencia>
            <madrid/>
        </ciudad_procedencia>
    </futuro>  

    <divisa precio="Euro" estable="si">
        <nombre_divisa>Peso</nombre_divisa>
        <tipo_de_cambio>Dolar</tipo_de_cambio>
        <ciudad_procedencia>
            <madrid/>
        </ciudad_procedencia>
    </divisa>

    <bono precio="5">
        <pais_de_procedencia>Colombia</pais_de_procedencia>
        <valor_deseado>7</valor_deseado>
        <valor_minimo>1</valor_minimo>
        <valor_maximo>10</valor_maximo>
        <ciudad_procedencia>
            <madrid/>
        </ciudad_procedencia>
    </bono>
        
    <letra precio="A">
        <tipo_de_interes>Mucho</tipo_de_interes>
        <pais_emisor>
            <eeuu/>
        </pais_emisor>
        <ciudad_procedencia>
            <madrid/>
        </ciudad_procedencia>
    </letra>
</listado>
